import type { RequestLocation } from '@/api'

// 常用出口城市预设，地区字段使用上游识别的行政区名称
const rows = [
  ['US', 'California', 'Los Angeles', 'America/Los_Angeles', '洛杉矶'],
  ['US', 'California', 'San Francisco', 'America/Los_Angeles', '旧金山'],
  ['US', 'Washington', 'Seattle', 'America/Los_Angeles', '西雅图'],
  ['US', 'New York', 'New York', 'America/New_York', '纽约'],
  ['US', 'Virginia', 'Ashburn', 'America/New_York', '阿什本'],
  ['US', 'Illinois', 'Chicago', 'America/Chicago', '芝加哥'],
  ['US', 'Texas', 'Dallas', 'America/Chicago', '达拉斯'],
  ['US', 'Colorado', 'Denver', 'America/Denver', '丹佛'],
  ['US', 'Arizona', 'Phoenix', 'America/Phoenix', '凤凰城'],
  ['US', 'Hawaii', 'Honolulu', 'Pacific/Honolulu', '檀香山'],
  ['CA', 'Ontario', 'Toronto', 'America/Toronto', '多伦多'],
  ['CA', 'British Columbia', 'Vancouver', 'America/Vancouver', '温哥华'],
  ['CA', 'Quebec', 'Montreal', 'America/Toronto', '蒙特利尔'],
  ['GB', 'England', 'London', 'Europe/London', '伦敦'],
  ['DE', 'Hesse', 'Frankfurt', 'Europe/Berlin', '法兰克福'],
  ['DE', 'Berlin', 'Berlin', 'Europe/Berlin', '柏林'],
  ['FR', 'Île-de-France', 'Paris', 'Europe/Paris', '巴黎'],
  ['NL', 'North Holland', 'Amsterdam', 'Europe/Amsterdam', '阿姆斯特丹'],
  ['FI', 'Uusimaa', 'Helsinki', 'Europe/Helsinki', '赫尔辛基'],
  ['SE', 'Stockholm', 'Stockholm', 'Europe/Stockholm', '斯德哥尔摩'],
  ['CH', 'Zurich', 'Zurich', 'Europe/Zurich', '苏黎世'],
  ['IE', 'Leinster', 'Dublin', 'Europe/Dublin', '都柏林'],
  ['ES', 'Community of Madrid', 'Madrid', 'Europe/Madrid', '马德里'],
  ['IT', 'Lombardy', 'Milan', 'Europe/Rome', '米兰'],
  ['PL', 'Masovian', 'Warsaw', 'Europe/Warsaw', '华沙'],
  ['JP', 'Tokyo', 'Tokyo', 'Asia/Tokyo', '东京'],
  ['JP', 'Osaka', 'Osaka', 'Asia/Tokyo', '大阪'],
  ['KR', 'Seoul', 'Seoul', 'Asia/Seoul', '首尔'],
  ['SG', 'Singapore', 'Singapore', 'Asia/Singapore', '新加坡'],
  ['HK', 'Hong Kong', 'Hong Kong', 'Asia/Hong_Kong', '香港'],
  ['TW', 'Taipei', 'Taipei', 'Asia/Taipei', '台北'],
  ['CN', 'Beijing', 'Beijing', 'Asia/Shanghai', '北京'],
  ['CN', 'Shanghai', 'Shanghai', 'Asia/Shanghai', '上海'],
  ['CN', 'Guangdong', 'Guangzhou', 'Asia/Shanghai', '广州'],
  ['CN', 'Guangdong', 'Shenzhen', 'Asia/Shanghai', '深圳'],
  ['CN', 'Zhejiang', 'Hangzhou', 'Asia/Shanghai', '杭州'],
  ['CN', 'Sichuan', 'Chengdu', 'Asia/Shanghai', '成都'],
  ['AU', 'New South Wales', 'Sydney', 'Australia/Sydney', '悉尼'],
  ['AU', 'Victoria', 'Melbourne', 'Australia/Melbourne', '墨尔本'],
  ['AU', 'Western Australia', 'Perth', 'Australia/Perth', '珀斯'],
  ['NZ', 'Auckland', 'Auckland', 'Pacific/Auckland', '奥克兰'],
  ['IN', 'Maharashtra', 'Mumbai', 'Asia/Kolkata', '孟买'],
  ['IN', 'Delhi', 'New Delhi', 'Asia/Kolkata', '新德里'],
  ['TH', 'Bangkok', 'Bangkok', 'Asia/Bangkok', '曼谷'],
  ['MY', 'Kuala Lumpur', 'Kuala Lumpur', 'Asia/Kuala_Lumpur', '吉隆坡'],
  ['ID', 'Jakarta', 'Jakarta', 'Asia/Jakarta', '雅加达'],
  ['PH', 'Metro Manila', 'Manila', 'Asia/Manila', '马尼拉'],
  ['VN', 'Ho Chi Minh City', 'Ho Chi Minh City', 'Asia/Ho_Chi_Minh', '胡志明市'],
  ['AE', 'Dubai', 'Dubai', 'Asia/Dubai', '迪拜'],
  ['IL', 'Tel Aviv', 'Tel Aviv', 'Asia/Jerusalem', '特拉维夫'],
  ['TR', 'Istanbul', 'Istanbul', 'Europe/Istanbul', '伊斯坦布尔'],
  ['BR', 'São Paulo', 'São Paulo', 'America/Sao_Paulo', '圣保罗'],
  ['MX', 'Mexico City', 'Mexico City', 'America/Mexico_City', '墨西哥城'],
  ['CL', 'Santiago', 'Santiago', 'America/Santiago', '圣地亚哥'],
  ['ZA', 'Gauteng', 'Johannesburg', 'Africa/Johannesburg', '约翰内斯堡'],
] as const

export const requestLocations: (RequestLocation & { label: string })[] = rows.map(([country, region, city, timezone, label]) => ({ country, region, city, timezone, label }))
